refactor: modules.format_title bracket logic improved
- Underscores in bracket title now convert to space (spaces are unchange but discouraged)

- Introduce escape character '%' to bracket title mode

- New config var 'PLAN__MODULES_ENFORCE_TITLE' which if true fails on improper title format

- Update README description

diff --git a/src/planit/planit b/src/planit/planit
--- a/src/planit/planit
+++ b/src/planit/planit
@@ -145,8 +145,13 @@ for ((i = init_module_idx; i < "${#PLAN__MODULES[@]}"; i++)); do
 
         if [ -z "$PLAN__MODULE_TITLE" ]; then
             PLAN__MODULE_TITLE="$(Plan::modules.format_title "$module")"
-            [ -z "$PLAN__MODULE_TITLE" ] \
-                && PLAN__MODULE_TITLE="$PLAN__MODULES_DEFAULT_TITLE (#$((i + 1)))"
+            if [ -z "$PLAN__MODULE_TITLE" ]; then
+                if [ "$PLAN__MODULES_ENFORCE_TITLE" == 'true' ]; then
+                    Plan::log.error "Invalid module title '$module'"
+                    exit 1
+                fi
+                PLAN__MODULE_TITLE="$PLAN__MODULES_DEFAULT_TITLE (#$((i + 1)))"
+            fi
         fi
 
         /usr/bin/env bash "$module" \
